services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: api_producer
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./gcp-credentials.json:/app/gcp-credentials.json
      - ./backend:/app/backend
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: worker_consumer
    command: python -m backend.queue.worker
    env_file:
      - .env
    volumes:
      - ./gcp-credentials.json:/app/gcp-credentials.json
      - ./backend:/app/backend
    depends_on:
      - redis
    deploy:
      replicas: 1

  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_hiring_frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules